sim_config:
  dt: 0.01
  time_horizon: 600
  seed: 42

priority_config:
  responsible_controller: micro
  priority_method: even
  evs: all

pcc:
  name: pcc
  update_interval_s: 1.0
  set_delay_s: 0.5

central_controller:
  type: ConstantCentralController
  params:
    name: cc
    init_p_setpoint: 20.0
    update_interval_s: Null
    set_delay_s: Null
    get_delay_s: Null
    calculation_delay_s: Null

micro_controllers:
  type: RuleBasedMicroController
  params:
    init_p_setpoint: 0.0
    compensation_factor: 0.1
    update_interval_s: 2.0
    set_delay_s: 0.5
    get_delay_s: 0.5
    calculation_delay_s: Null
    i_min: 6.0
    i_rounding_method: floor
    i_granularity: 1.0

chargers:
  type: IntegratedCharger
  params:
    init_p_setpoint: 0.0
    set_delay_s: 0.5
    get_delay_s: 0.5
    charger_config: wattpilot_22.yaml
    i_min: 6.0
    i_rounding_method: floor
    i_granularity: 1.0

evs:
  - name: skoda
    arrival_time: 0
    departure_time: 400
    e_required_kwh: 10.0
    init_soc: 0.0
    ev_config: skoda_enyaq_iV60_2021.yaml

  - name: tesla
    arrival_time: 50
    departure_time: 600
    e_required_kwh: 7.5
    init_soc: 0.0
    ev_config: tesla_model3_LRDM_2020.yaml

  - name: vw
    arrival_time: 200
    departure_time: 300
    e_required_kwh: 7.5
    init_soc: 0.0
    ev_config: vw_id3_pro_2022.yaml